version: '2'
services:
  web:
    image: ianhilt/pdibackend:latest
    ports:
      - "8080:80"
    environment:
      DB_HOST: db
      DB_PORT: ""
      DB_PREFIX: "myoctober_"
      DB_PASSWORD: "my-secret-pw"
      DB_USER: "root"
      DB_NAME: "october_cms"
      LINK_POLICY: 'detect'
      OCTOBER_DEBUG: 'true'
      REDIS_HOST: redis_session_storage
    depends_on:
      - redis_session_storage
      - db
    entrypoint: /wait-for-it.sh db:3306 -- /run.sh
  redis_session_storage:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
      MYSQL_DATABASE: 'october_cms'
